name: build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        rust:
          - stable
          # - beta
          - nightly
        linker:
          - system
          - lld
          - mold

    name: ${{ matrix.rust }} (${{ matrix.linker }})
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}

      - name: Install dependencies
        run: sudo apt-get -y update; sudo apt install -y g++ gcc

      - name: Install linker
        if: matrix.linker != 'system'
        run: sudo apt install -y ${{ matrix.linker }}

      - name: Build
        run: |
          case ${{ matrix.linker }} in
            system)
              cargo build --all --all-targets --release
              ;;
            *)
              RUSTFLAGS="-C link-arg=-fuse-ld=${{ matrix.linker }}" cargo build --all --all-targets --release
              ;;
          esac

      # cargo build --all --all-targets --release --target-dir target-${{ matrix.linker }}
