name: ci

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  format:
    name: format
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
          override: true
      - name: Check formatting
        run: cargo fmt --all --check

  lint:
    name: lint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true
      - name: Check clippy
        run: cargo clippy --all --all-targets -- -D warnings
